FROM python:3.8

WORKDIR /app

RUN apt-get update -y && apt-get install -y default-jdk && apt-get clean

ENV JAVA_HOME=/usr/lib/jvm/default-java
ENV PATH=$JAVA_HOME/bin:$PATH

RUN pip install pandas pyspark kafka-python

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

CMD ["python", "producer.py"]

